[package]
name = "erno-cube-solver"
version = "0.1.0"
authors = ["Yangxi-FAN <yxfan@thoughtworks.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
